Смена element.search.strategy на soft или any, multiple не влияет на поиск
Несмотря на то, что element.search.strategy=soft или any, multiple
ошибка:
java.lang.RuntimeException: [12:25.51] Failed to execute 'UIElement.click' for element 'locator' during '10' seconds. Found 2 elements instead of one for Element 'locator (xpath='locator')' during 10 seconds
по прежнему выдается.

Воспроизводится, как в случае если локатор начинается с $, так и в случае, если вынесен в переменную с аннотацией